module.exports = {
  data : [
    {
      name:'价格',
      multi:'0',//是否支持多选，0单选，1多选
      conList:[
        {
          id:1,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'1-100',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:2,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'101-500',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:3,//属性id
          selected:1,//1代表选中，0代表未选中
          value:'501-2000',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:4,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'501-2000',
          disabled:'0',//0代表不可选，1代表可以选中
        },
        {
          id:5,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'501-2000',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:6,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'12000以上',
          disabled:'1',//0代表不可选，1代表可以选中
        },
      ],
    },
    {
      name:'品牌',
      multi:'1',
      conList:[
        {
          id:7,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'苹果',
          disabled:'0',//0代表不可选，1代表可以选中
        },
        {
          id:8,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'三星',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:9,//属性id
          selected:1,//1代表选中，0代表未选中
          value:'诺基亚',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:10,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'华为',
          disabled:'1',//0代表不可选，1代表可以选中
        },
      ],
    },
    {
      name:'网络类型',
      multi:'0',
      conList:[
        {
          id:11,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'全网支持',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:12,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'联通4G',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:13,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'移动4G',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:14,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'电信4G',
          disabled:'1',//0代表不可选，1代表可以选中
        },
      ],
    },
    {
      name:'像素',
      multi:'0',
      conList:[
        {
          id:15,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'1000-2000',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:16,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'1000-2000',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:17,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'4000-6000',
          disabled:'1',//0代表不可选，1代表可以选中
        },
        {
          id:18,//属性id
          selected:0,//1代表选中，0代表未选中
          value:'6000-8000',
          disabled:'1',//0代表不可选，1代表可以选中
        },
      ],
    }
  ],
}


