module.exports = {
      data :[
        {
            id:'0',
            name:'手机数码',
        },
        {
            id:'1',
            name:'家用电器',
        },
        {
            id:'2',
            name:'家居生活',
        },

        {
            id:'3',
            name:'综合百货',
        },
        {
            id:'4',
            name:'时尚美女',
        },
        {
            id:'5',
            name:'腕表珠宝',
        },
        {
            id:'6',
            name:'母婴玩具',
        },
        {
            id:'7',
            name:'奢侈品',
        },
    ],
    data2 : [
    	[
	        {
	            name: '手机',
	            data:[
	                {
	                    name:'手机',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'111',
	                },
	                {
	                    name:'手机',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'112',
	                },
	            ]
	        },
	        {
	            name: '手机配件',
	            data:[
	                {
	                    name:'手机1',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'113',
	                },
	                {
	                    name:'手机2',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'114',
	                },
	            ]
	        }
	    ],
	    [
	        {
	            name: '电器',
	            data:[
	                {
	                    name:'电脑',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'115',
	                },
	                {
	                    name:'电脑',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'116',
	                },
	            ]
	        },
	        {
	            name: '电冰箱',
	            data:[
	                {
	                    name:'电冰箱',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'117',
	                },
	            ]
	        },
	        {
	            name: '洗衣机',
	            data:[
	                {
	                    name:'洗衣机',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'118',
	                },
	            ]
	        },
	    ],
	    [
	        {
	            name: '生活',
	            data:[
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'119',
	                },
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'120',
	                },
	            ]
	        },
	    ],
	    [
	        {
	            name: '综合百货',
	            data:[
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'121',
	                },
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'122',
	                },
	            ]
	        },
	    ],
	    [
	        {
	            name: '时尚美女',
	            data:[
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'123',
	                },
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'124',
	                },
	            ]
	        },
	    ],
	    [
	        {
	            name: '腕表珠宝',
	            data:[
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'125',
	                },
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'126',
	                },
	            ]
	        },
	    ],
	    [
	        {
	            name: '母婴玩具',
	            data:[
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'127',
	                },
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'129',
	                },
	            ]
	        },
	    ],
	    [
	        {
	            name: '奢侈品',
	            data:[
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'130',
	                },
	                {
	                    name:'生活',
	                    img:{
	                        name:'',
	                        src:'_/vue/image/demo.jpg'
	                    },
	                    id:'131',
	                },
	            ]
	        },
	    ],
    ],
}